server:
  port: 8088
  servlet:
    path: /
logging:
  level:
    com.zxg: debug
    #org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.184.130:3306/yun6
    username: root
    password: root
#通用Mapper mabtis 整合
mybatis:
  #mapper-locations: mapper/*.xml
  type-aliases-package: com.zxg.pojo